### PR TITLE
Add library.json

### PR DESCRIPTION
**Pull request by ellsclytn**
This would allow this library to appear in the [PlatformIO library manager](http://docs.platformio.org/en/latest/librarymanager/). I've looked through the [`library.json` spec](http://docs.platformio.org/en/latest/librarymanager/config.html) and added everything that I can think of.

### CODE REVIEW

**Comment by ivankravets** [comment]
@ellsclytn  thanks! http://platformio.org/lib/show/275/Rotary

**Comment by per1234** [comment]
You might consider adding a [library.properties](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format) file instead of library.json. The reason being that this file [will work with both the Arduino IDE and Platformio](https://docs.platformio.org/en/latest/userguide/lib/cmd_register.html#description).

**Comment by brianlow** [comment]
Seems like `library.properties` is the way to go? Supports the wider Arduino community vs a single vendor.

**Comment by ivankravets** [comment]
This is an old PR by @ellsclytn (2016 year). We added support for `library.properties` in 2017 if I remember correctly.

@PlatformIO supports a lot of different manifests including `library.properties`. If you don't need extra configuration for your library, `library.properties` is a good choice. 

Please ping me here when `library.properties` will be ready, we will switch your library to this manifest.

**Pull request closed without merging**
