### PR TITLE
fixed: inverter = 0 causes unexpected pinstate value

### PR DESCRIPTION
**Pull request by snt**
I am using pull-up circuit with your library and it does not work well.
This is because the code has `inverter - digitalRead(...)` and it will be `255` instead of `0` if the return value of `digitalRead(...)` is `1`. 
`inverter ^ digitalRead(...)` should return expected inverted value.

### CODE REVIEW

**Comment by voneiden** [comment]
Seems good to me. @MortalFool fyi. I'll go ahead and merge this soon if there are no objections.

**Review by brianlow — APPROVED** [review]
Thanks for this fix!

**Comment by snt** [comment]
👍 Thanks!

**Review by voneiden — APPROVED** [review]

**Comment by voneiden** [comment]
Reopened so I can actually merge this :-)

**Comment by snt** [comment]
oops :-)

**Comment by MortalFool** [comment]
Sorry, I'm late to the party, but, yes, you are all totally right, of course. (And apologies again for another regression I introduced. I promise, I'll be more careful next time... <sigh>)

**Comment by brianlow** [comment]
@MortalFool no worries, appreciate the contribution. 

I wonder if there is anything like automated tests / CI for Arduino?Maybe a simulator?

**Pull request merged**
