### PR TITLE
Decouple internal pull-up use from pin inversion for pull-down use

### PR DESCRIPTION
**Pull request by MortalFool**
Add dedicated parameter for inverting pin logic when using pull-downs.

### CODE REVIEW

**Comment by MortalFool** [comment]
I was a bit torn between adding an additional parameter (along with a default value) as opposed to adding an enum-like option (like PULLUP_INTERNAL, PULLUP_EXTERNAL, and PULLDOWN_EXTERNAL). The latter would prohibit "invalid" configurations like using internal pull-ups with logic inversion, but would break backwards compatibility, so went with the former.

@brianlow What do you think?

**Comment by brianlow** [comment]
Thanks for the PR @MortalFool. Why would PULLDOWN_EXTERNAL not be a valid combination?

**Comment by MortalFool** [comment]
No, PULLDOWN_EXTERNAL would be totally valid - I'm not sure about being able to call `rotary.begin(true, true);`, though, as that would enable the internal pull-up, but still flip the logic (as for use with pull-downs). I don't think it's a big issue, but I still wanted to point this out.

Does that make sense?

**Comment by brianlow** [comment]
Is that situation unlikely because encoders are never built that way? I'm just a hobbyist so some of this is unfamiliar.  Perhaps some notes in the readme to steer people away from `true`, `true` combination?

Merging because I think this solves the regression (thanks again!)

**Comment by brianlow** [comment]
@MortalFool up to you! If you are up for it and think it will help someone else

**Comment by MortalFool** [comment]
I gave it a shot in #17 (but it might be a bit unwieldy :sweat_smile:...)

**Pull request merged**
