### PR TITLE
Move example sketch to its own folder

### PR DESCRIPTION
**Pull request by per1234**
The Arduino IDE opens all files from a sketch folder as tabs of one project. So multiple sketches in the same folder causes compilation to fail with "redefinition of" errors.

### CODE REVIEW

**Comment by brianlow** [comment]
Thanks! I don't have a Arduino env up right now. I'll merge as long as someone can double-check.

**Comment by rolfmeurer** [comment]
I agree, but it's easy to delete the useless tab . this library works pretty well!

**Comment by per1234** [comment]
@rolfmeurer maybe it's easy for you to delete the useless tab, but for many Arduino users this will result in a ton of confusion before they figure out that they need to do that to fix the compilation error. Also, the Arduino IDE makes this difficult to do since library examples are treated as read-only and if you try to delete the "Interrupt" tab it deletes both files.

@brianlow I don't understand what there is to "double-check". Surely you know how Arduino sketches work? Each sketch needs to be in its own folder, which matches the name of the primary sketch file. The need for this change should be obvious after 5 seconds of looking at the diff. There's absolutely nothing controversial about this.

These are the error messages when you compile the example as it is currently:
```
InterruptProMicro:25:8: error: redefinition of 'Rotary r'

 Rotary r = Rotary(8, 9);

        ^

E:\electronics\arduino\libraries\Rotary\examples\Interrupt\Interrupt.ino:12:8: note: 'Rotary r' previously declared here

 Rotary r = Rotary(2, 3);

        ^

E:\electronics\arduino\libraries\Rotary\examples\Interrupt\InterruptProMicro.ino: In function 'void setup()':

InterruptProMicro:27:6: error: redefinition of 'void setup()'

 void setup() {

      ^

E:\electronics\arduino\libraries\Rotary\examples\Interrupt\Interrupt.ino:14:6: note: 'void setup()' previously defined here

 void setup() {

      ^

E:\electronics\arduino\libraries\Rotary\examples\Interrupt\InterruptProMicro.ino: In function 'void loop()':

InterruptProMicro:34:6: error: redefinition of 'void loop()'

 void loop() {

      ^

E:\electronics\arduino\libraries\Rotary\examples\Interrupt\Interrupt.ino:21:6: note: 'void loop()' previously defined here

 void loop() {

      ^
```

**Comment by brianlow** [comment]
You are right, thanks for the PR!

**Pull request merged**
